spring:
  application:
    name: currency-exchange-service
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
    password: as
    initialization-mode: always
  jpa:
    show-sql: true
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    #open-in-view: true
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true
      settings:
        trace: true
        web-allow-others: true
server:
  port: 8001
  servlet:
    context-path: /exchange-service
